# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Markdown Lint

on:
  push:
    paths: ["**.md"]
  pull_request:
    paths: ["**.md"]

env:
  dotnetVersion: "6.0.x"

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **.md
            !src/**
